import type { ToolboxItem } from '../types/formDesigner';

// Toolbox configuration with all available field types
export const TOOLBOX_ITEMS: ToolboxItem[] = [
  // ========== BASIC FIELDS ==========
  {
    id: 'section',
    type: 'section',
    label: 'Sección',
    icon: 'segment',
    description: 'Separador visual con título para organizar el formulario',
    category: 'basic',
    defaultConfig: {
      type: 'section',
      label: 'Nueva Sección',
      required: false,
      span: { cols: 4 },
      helpText: 'Agrupa campos relacionados bajo un título',
    },
  },
  {
    id: 'text',
    type: 'text',
    label: 'Texto',
    icon: 'text_fields',
    description: 'Campo de texto simple',
    category: 'basic',
    defaultConfig: {
      type: 'text',
      label: 'Campo de texto',
      placeholder: 'Ingrese texto...',
      required: false,
      span: { cols: 2 },
    },
  },
  {
    id: 'number',
    type: 'number',
    label: 'Número',
    icon: 'pin',
    description: 'Campo numérico',
    category: 'basic',
    defaultConfig: {
      type: 'number',
      label: 'Número',
      placeholder: '0',
      required: false,
      span: { cols: 1 },
    },
  },
  {
    id: 'email',
    type: 'email',
    label: 'Email',
    icon: 'email',
    description: 'Campo de correo electrónico',
    category: 'basic',
    defaultConfig: {
      type: 'email',
      label: 'Correo electrónico',
      placeholder: 'correo@ejemplo.com',
      required: false,
      span: { cols: 2 },
      validation: {
        pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
        message: 'Ingrese un email válido',
      },
    },
  },
  {
    id: 'phone',
    type: 'phone',
    label: 'Teléfono',
    icon: 'phone',
    description: 'Campo de número telefónico',
    category: 'basic',
    defaultConfig: {
      type: 'phone',
      label: 'Teléfono',
      placeholder: '+1 (555) 000-0000',
      required: false,
      span: { cols: 1 },
    },
  },
  {
    id: 'textarea',
    type: 'textarea',
    label: 'Área de texto',
    icon: 'notes',
    description: 'Campo de texto multilínea',
    category: 'basic',
    defaultConfig: {
      type: 'textarea',
      label: 'Comentarios',
      placeholder: 'Escriba aquí...',
      required: false,
      span: { cols: 4 },
    },
  },
  {
    id: 'select',
    type: 'select',
    label: 'Selección',
    icon: 'arrow_drop_down_circle',
    description: 'Lista desplegable de opciones',
    category: 'basic',
    defaultConfig: {
      type: 'select',
      label: 'Seleccione una opción',
      placeholder: 'Seleccionar...',
      required: false,
      span: { cols: 2 },
      options: ['Opción 1', 'Opción 2', 'Opción 3'],
    },
  },
  {
    id: 'checkbox',
    type: 'checkbox',
    label: 'Casilla',
    icon: 'check_box',
    description: 'Casilla de verificación',
    category: 'basic',
    defaultConfig: {
      type: 'checkbox',
      label: 'Acepto los términos',
      required: false,
      span: { cols: 2 },
    },
  },
  {
    id: 'radio',
    type: 'radio',
    label: 'Opciones',
    icon: 'radio_button_checked',
    description: 'Grupo de opciones excluyentes',
    category: 'basic',
    defaultConfig: {
      type: 'radio',
      label: 'Seleccione una opción',
      required: false,
      span: { cols: 2 },
      options: ['Opción A', 'Opción B', 'Opción C'],
    },
  },

  // ========== ADVANCED FIELDS ==========
  {
    id: 'date',
    type: 'date',
    label: 'Fecha',
    icon: 'calendar_today',
    description: 'Selector de fecha',
    category: 'advanced',
    defaultConfig: {
      type: 'date',
      label: 'Fecha',
      required: false,
      span: { cols: 1 },
    },
  },
  {
    id: 'datetime',
    type: 'datetime',
    label: 'Fecha y Hora',
    icon: 'event',
    description: 'Selector de fecha y hora',
    category: 'advanced',
    defaultConfig: {
      type: 'datetime',
      label: 'Fecha y hora',
      required: false,
      span: { cols: 2 },
    },
  },
  {
    id: 'time',
    type: 'time',
    label: 'Hora',
    icon: 'schedule',
    description: 'Selector de hora',
    category: 'advanced',
    defaultConfig: {
      type: 'time',
      label: 'Hora',
      required: false,
      span: { cols: 1 },
    },
  },
  {
    id: 'file',
    type: 'file',
    label: 'Archivo',
    icon: 'attach_file',
    description: 'Carga de archivos',
    category: 'advanced',
    defaultConfig: {
      type: 'file',
      label: 'Adjuntar archivo',
      required: false,
      span: { cols: 2 },
    },
  },
  {
    id: 'image',
    type: 'image',
    label: 'Imagen',
    icon: 'image',
    description: 'Carga de imágenes',
    category: 'advanced',
    defaultConfig: {
      type: 'image',
      label: 'Subir imagen',
      required: false,
      span: { cols: 2 },
    },
  },
  {
    id: 'color',
    type: 'color',
    label: 'Color',
    icon: 'palette',
    description: 'Selector de color',
    category: 'advanced',
    defaultConfig: {
      type: 'color',
      label: 'Color',
      required: false,
      span: { cols: 1 },
      defaultValue: '#4db8b8',
    },
  },
  {
    id: 'url',
    type: 'url',
    label: 'URL',
    icon: 'link',
    description: 'Campo de URL',
    category: 'advanced',
    defaultConfig: {
      type: 'url',
      label: 'Sitio web',
      placeholder: 'https://ejemplo.com',
      required: false,
      span: { cols: 2 },
      validation: {
        pattern: '^https?://.+',
        message: 'Ingrese una URL válida',
      },
    },
  },
  {
    id: 'slider',
    type: 'slider',
    label: 'Deslizador',
    icon: 'tune',
    description: 'Control deslizante para rangos',
    category: 'advanced',
    defaultConfig: {
      type: 'slider',
      label: 'Valor',
      required: false,
      span: { cols: 2 },
      validation: {
        min: 0,
        max: 100,
      },
      defaultValue: 50,
    },
  },
  {
    id: 'repeater',
    type: 'repeater',
    label: 'Grupo Repetitivo',
    icon: 'repeat',
    description: 'Grupo de campos que se pueden repetir múltiples veces',
    category: 'advanced',
    defaultConfig: {
      type: 'repeater',
      label: 'Grupo Repetitivo',
      required: false,
      span: { cols: 4 },
      helpText: 'Los usuarios podrán agregar múltiples instancias de este grupo',
      repeaterConfig: {
        fields: [
          {
            type: 'text',
            label: 'Campo 1',
            name: 'field1',
            placeholder: 'Ingrese texto...',
          },
          {
            type: 'text',
            label: 'Campo 2',
            name: 'field2',
            placeholder: 'Ingrese texto...',
          },
        ],
        minItems: 0,
        maxItems: 10,
        addButtonText: 'Agregar',
        removeButtonText: 'Eliminar',
        itemLabelTemplate: 'Elemento {index}',
      },
    },
  },

  // ========== SPECIALIZED FIELDS ==========
  {
    id: 'address',
    type: 'address',
    label: 'Dirección',
    icon: 'home',
    description: 'Campo compuesto para dirección completa',
    category: 'specialized',
    defaultConfig: {
      type: 'address',
      label: 'Dirección',
      required: false,
      span: { cols: 4 },
      helpText: 'Incluye calle, ciudad, estado y país',
    },
  },
  {
    id: 'location',
    type: 'location',
    label: 'Ubicación GPS',
    icon: 'place',
    description: 'Coordenadas geográficas con mapa',
    category: 'specialized',
    defaultConfig: {
      type: 'location',
      label: 'Ubicación',
      required: false,
      span: { cols: 4 },
      helpText: 'Seleccione una ubicación en el mapa',
    },
  },
  {
    id: 'signature',
    type: 'signature',
    label: 'Firma',
    icon: 'draw',
    description: 'Campo para firma digital',
    category: 'specialized',
    defaultConfig: {
      type: 'signature',
      label: 'Firma',
      required: false,
      span: { cols: 3 },
      helpText: 'Dibuje su firma en el recuadro',
    },
  },
  {
    id: 'rating',
    type: 'rating',
    label: 'Calificación',
    icon: 'star',
    description: 'Sistema de calificación con estrellas',
    category: 'specialized',
    defaultConfig: {
      type: 'rating',
      label: 'Calificación',
      required: false,
      span: { cols: 2 },
      validation: {
        min: 1,
        max: 5,
      },
    },
  },
  {
    id: 'tags',
    type: 'tags',
    label: 'Etiquetas',
    icon: 'label',
    description: 'Campo de etiquetas múltiples',
    category: 'specialized',
    defaultConfig: {
      type: 'tags',
      label: 'Etiquetas',
      placeholder: 'Escriba y presione Enter',
      required: false,
      span: { cols: 3 },
    },
  },
];

// Group items by category for display
export const TOOLBOX_CATEGORIES = {
  basic: TOOLBOX_ITEMS.filter((item) => item.category === 'basic'),
  advanced: TOOLBOX_ITEMS.filter((item) => item.category === 'advanced'),
  specialized: TOOLBOX_ITEMS.filter((item) => item.category === 'specialized'),
};

// Get toolbox item by type
export const getToolboxItem = (type: string): ToolboxItem | undefined => {
  return TOOLBOX_ITEMS.find((item) => item.type === type);
};
