// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharMind.API.Data;

#nullable disable

namespace PharMind.API.Migrations
{
    [DbContext(typeof(PharMindDbContext))]
    [Migration("20251102053442_AddTablasMaestras")]
    partial class AddTablasMaestras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharMind.API.Models.Empresa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("CUIT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CUIT");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Logo");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("RazonSocial");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.HasIndex("CUIT")
                        .IsUnique()
                        .HasFilter("[CUIT] IS NOT NULL");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = "EMP-DEFAULT-001",
                            Activo = true,
                            CUIT = "20-12345678-9",
                            Email = "info@pharmind.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "PharMind",
                            RazonSocial = "PharMind S.A.",
                            Status = false
                        });
                });

            modelBuilder.Entity("PharMind.API.Models.EntidadDinamica", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Datos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Datos");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EmpresaId");

                    b.Property<string>("EsquemaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EsquemaId");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("FullDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FullDescription");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ModificadoPor");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tags");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EsquemaId");

                    b.ToTable("EntidadesDinamicas");
                });

            modelBuilder.Entity("PharMind.API.Models.EsquemaPersonalizado", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Color");

                    b.Property<string>("ConfiguracionUI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConfiguracionUI");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EmpresaId");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EntidadTipo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Icono");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<int?>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("Orden");

                    b.Property<string>("ReglasCorrelacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReglasCorrelacion");

                    b.Property<string>("ReglasValidacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReglasValidacion");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Schema");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<string>("SubTipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SubTipo");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "EntidadTipo", "SubTipo")
                        .IsUnique()
                        .HasFilter("[EmpresaId] IS NOT NULL AND [SubTipo] IS NOT NULL");

                    b.ToTable("EsquemasPersonalizados");
                });

            modelBuilder.Entity("PharMind.API.Models.Modulo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Icono");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("ModuloPadreId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ModuloPadreId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("Orden");

                    b.Property<string>("Ruta")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Ruta");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("ModuloPadreId");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = "MOD-USUARIOS-001",
                            Activo = true,
                            Descripcion = "Gestión de usuarios del sistema",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icono = "people",
                            Nombre = "Usuarios",
                            Orden = 1,
                            Ruta = "/usuarios",
                            Status = false
                        },
                        new
                        {
                            Id = "MOD-ROLES-001",
                            Activo = true,
                            Descripcion = "Gestión de roles y permisos",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icono = "admin_panel_settings",
                            Nombre = "Roles",
                            Orden = 2,
                            Ruta = "/roles",
                            Status = false
                        },
                        new
                        {
                            Id = "MOD-EMPRESAS-001",
                            Activo = true,
                            Descripcion = "Gestión de empresas",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icono = "business",
                            Nombre = "Empresas",
                            Orden = 3,
                            Ruta = "/empresas",
                            Status = false
                        });
                });

            modelBuilder.Entity("PharMind.API.Models.Rol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("EmpresaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EmpresaId");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("bit")
                        .HasColumnName("EsSistema");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "ROL-ADMIN-001",
                            Activo = true,
                            Descripcion = "Acceso total al sistema",
                            EmpresaId = "EMP-DEFAULT-001",
                            EsSistema = true,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador",
                            Status = false
                        });
                });

            modelBuilder.Entity("PharMind.API.Models.RolModulo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CreadoPor");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("ModuloId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ModuloId");

                    b.Property<string>("NivelAcceso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NivelAcceso");

                    b.Property<bool>("PuedeAprobar")
                        .HasColumnType("bit")
                        .HasColumnName("PuedeAprobar");

                    b.Property<bool>("PuedeCrear")
                        .HasColumnType("bit")
                        .HasColumnName("PuedeCrear");

                    b.Property<bool>("PuedeEditar")
                        .HasColumnType("bit")
                        .HasColumnName("PuedeEditar");

                    b.Property<bool>("PuedeEliminar")
                        .HasColumnType("bit")
                        .HasColumnName("PuedeEliminar");

                    b.Property<bool>("PuedeExportar")
                        .HasColumnType("bit")
                        .HasColumnName("PuedeExportar");

                    b.Property<bool>("PuedeImportar")
                        .HasColumnType("bit")
                        .HasColumnName("PuedeImportar");

                    b.Property<bool>("PuedeVer")
                        .HasColumnType("bit")
                        .HasColumnName("PuedeVer");

                    b.Property<string>("RolId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RolId");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("RolId");

                    b.ToTable("RolModulos");

                    b.HasData(
                        new
                        {
                            Id = "ROLMOD-ADMIN-USR-001",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModuloId = "MOD-USUARIOS-001",
                            NivelAcceso = "Administracion",
                            PuedeAprobar = true,
                            PuedeCrear = true,
                            PuedeEditar = true,
                            PuedeEliminar = true,
                            PuedeExportar = true,
                            PuedeImportar = true,
                            PuedeVer = true,
                            RolId = "ROL-ADMIN-001",
                            Status = false
                        },
                        new
                        {
                            Id = "ROLMOD-ADMIN-ROL-001",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModuloId = "MOD-ROLES-001",
                            NivelAcceso = "Administracion",
                            PuedeAprobar = true,
                            PuedeCrear = true,
                            PuedeEditar = true,
                            PuedeEliminar = true,
                            PuedeExportar = true,
                            PuedeImportar = true,
                            PuedeVer = true,
                            RolId = "ROL-ADMIN-001",
                            Status = false
                        },
                        new
                        {
                            Id = "ROLMOD-ADMIN-EMP-001",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModuloId = "MOD-EMPRESAS-001",
                            NivelAcceso = "Administracion",
                            PuedeAprobar = true,
                            PuedeCrear = true,
                            PuedeEditar = true,
                            PuedeEliminar = true,
                            PuedeExportar = true,
                            PuedeImportar = true,
                            PuedeVer = true,
                            RolId = "ROL-ADMIN-001",
                            Status = false
                        });
                });

            modelBuilder.Entity("PharMind.API.Models.TablaMaestra", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("EsquemaColumnas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EsquemaColumnas");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("NombreTabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NombreTabla");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<bool>("TablaCreada")
                        .HasColumnType("bit")
                        .HasColumnName("TablaCreada");

                    b.HasKey("Id");

                    b.ToTable("TablasMaestras");
                });

            modelBuilder.Entity("PharMind.API.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Avatar");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Cargo");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("bit")
                        .HasColumnName("EmailVerificado");

                    b.Property<string>("EmpresaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EmpresaId");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("ProveedorSSO")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProveedorSSO");

                    b.Property<string>("SSOId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SSOId");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Telefono");

                    b.Property<string>("TokenRecuperacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TokenRecuperacion");

                    b.Property<DateTime?>("TokenRecuperacionExpira")
                        .HasColumnType("datetime2")
                        .HasColumnName("TokenRecuperacionExpira");

                    b.Property<string>("TokenVerificacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TokenVerificacion");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimoAcceso");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = "USR-ADMIN-001",
                            Activo = true,
                            Email = "admin@pharmind.com",
                            EmailVerificado = true,
                            EmpresaId = "EMP-DEFAULT-001",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Administrador del Sistema",
                            PasswordHash = "$2a$11$HvE3qX5WzLJKN5/9YJX0x.JYWZXzJK5qKHJxZHJK5qKHJxZHJK5q.",
                            Status = false
                        });
                });

            modelBuilder.Entity("PharMind.API.Models.UsuarioRol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("AsignadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AsignadoPor");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CreadoPor");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAsignacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("RolId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RolId");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioRoles");

                    b.HasData(
                        new
                        {
                            Id = "USRROL-ADMIN-001",
                            FechaAsignacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RolId = "ROL-ADMIN-001",
                            Status = false,
                            UsuarioId = "USR-ADMIN-001"
                        });
                });

            modelBuilder.Entity("PharMind.API.Models.EntidadDinamica", b =>
                {
                    b.HasOne("PharMind.API.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("PharMind.API.Models.EsquemaPersonalizado", "Esquema")
                        .WithMany()
                        .HasForeignKey("EsquemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Esquema");
                });

            modelBuilder.Entity("PharMind.API.Models.EsquemaPersonalizado", b =>
                {
                    b.HasOne("PharMind.API.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PharMind.API.Models.Modulo", b =>
                {
                    b.HasOne("PharMind.API.Models.Modulo", "ModuloPadre")
                        .WithMany("SubModulos")
                        .HasForeignKey("ModuloPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ModuloPadre");
                });

            modelBuilder.Entity("PharMind.API.Models.Rol", b =>
                {
                    b.HasOne("PharMind.API.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PharMind.API.Models.RolModulo", b =>
                {
                    b.HasOne("PharMind.API.Models.Modulo", "Modulo")
                        .WithMany("RolModulos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharMind.API.Models.Rol", "Rol")
                        .WithMany("RolModulos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PharMind.API.Models.Usuario", b =>
                {
                    b.HasOne("PharMind.API.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PharMind.API.Models.UsuarioRol", b =>
                {
                    b.HasOne("PharMind.API.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharMind.API.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PharMind.API.Models.Modulo", b =>
                {
                    b.Navigation("RolModulos");

                    b.Navigation("SubModulos");
                });

            modelBuilder.Entity("PharMind.API.Models.Rol", b =>
                {
                    b.Navigation("RolModulos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("PharMind.API.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
