-- Eliminar tablas existentes
DROP TABLE IF EXISTS auditCategory;
DROP TABLE IF EXISTS auditCustomer;
DROP TABLE IF EXISTS auditPeriod;
DROP TABLE IF EXISTS auditProductClass;
DROP TABLE IF EXISTS auditMarketMarcas;

-- Recrear auditCategory basado en: CDG_PERUSER|CDGMED_REG|CDG_MERCADO|CDGREG_PMIX|CAT|PX_MER|PX_LAB|MER_MS|CDG_RAIZ|PX|PX_MS
CREATE TABLE auditCategory (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CDG_PERUSER NVARCHAR(100),
    CDGMED_REG NVARCHAR(100),
    CDG_MERCADO NVARCHAR(100),
    CDGREG_PMIX NVARCHAR(100),
    CAT NVARCHAR(500),
    PX_MER NVARCHAR(100),
    PX_LAB NVARCHAR(100),
    MER_MS NVARCHAR(100),
    CDG_RAIZ NVARCHAR(100),
    PX NVARCHAR(100),
    PX_MS NVARCHAR(100),
    RawData NVARCHAR(1000)
);

-- Recrear auditCustomer basado en: CDGMED_REG|CRM|NOME|BLANK|CDGESP1|CDGESP2|CDGREG_PMIX|LOCAL|BAIRRO|CEP|CDGMED_VIS
CREATE TABLE auditCustomer (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CDGMED_REG NVARCHAR(100),
    CRM NVARCHAR(100),
    NOME NVARCHAR(500),
    BLANK NVARCHAR(100),
    CDGESP1 NVARCHAR(100),
    CDGESP2 NVARCHAR(100),
    CDGREG_PMIX NVARCHAR(100),
    LOCAL NVARCHAR(500),
    BAIRRO NVARCHAR(200),
    CEP NVARCHAR(50),
    CDGMED_VIS NVARCHAR(100),
    RawData NVARCHAR(1000)
);

-- Recrear auditPeriod basado en: CDG_PERUSER|DESC|BLANK
CREATE TABLE auditPeriod (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CDG_PERUSER NVARCHAR(100),
    [DESC] NVARCHAR(500),
    BLANK NVARCHAR(100),
    RawData NVARCHAR(1000)
);

-- Recrear auditProductClass basado en: CODIGO_PMIX|CDG_MERCADO
CREATE TABLE auditProductClass (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CODIGO_PMIX NVARCHAR(100),
    CDG_MERCADO NVARCHAR(100),
    RawData NVARCHAR(1000)
);

-- Recrear auditMarketMarcas basado en: CODIGO|CODIGO_PMIX|NOME|SIGLALAB
CREATE TABLE auditMarketMarcas (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CODIGO NVARCHAR(100),
    CODIGO_PMIX NVARCHAR(100),
    NOME NVARCHAR(500),
    SIGLALAB NVARCHAR(100),
    RawData NVARCHAR(1000)
);

PRINT 'Tablas recreadas exitosamente';
